### ISSUE TITLE
Open a popover without user interaction

### ISSUE THREAD

**Issue by polyGeek** [minikin/popover#16]
Great package guys. Thanks!

One of the things I'd like to use Popover for is to display information to the user without them needing to tap on a button to see it. Then the user can tap the button to toggle the popover closed.

Is there a way to do this?

**Comment by minikin** [comment]
Thanks, @polyGeek, for the question. Sure, it should be possible.
I have an idea how to do so. I'll keep you updated on this thread.

**Comment by minikin** [comment]
@polyGeek please see an updated [example](https://github.com/minikin/popover/blob/main/example/lib/main.dart)
