### ISSUE TITLE
Is it possible to click outside the popover and hear to mouse events?

### ISSUE THREAD

**Issue by arualana** [minikin/popover#27]
While the popover is showing, I would like to be able to click on buttons on the page that are around it (behind the barrier but not behind the popover itself.

Is this possible please?
Thank you

**Comment by minikin** [comment]
@arualana Thank you for your request!
We probably can implement such behavior. However, I'd appreciate it if you can provide more concrete examples of why do we need to add this, please 🙏

**Comment by minikin** [comment]
Closing the issues due
