### ISSUE TITLE
Error setting full screen width display

### ISSUE THREAD

**Issue by superxsx** [minikin/popover#31]
1、The pop-up box displayed an error when I set this code：width: MediaQuery.of(context).size.width，as follow：
2、
![1619607442(1)](https://user-images.githubusercontent.com/32897328/116392924-a04bb480-a853-11eb-887d-92ac5631a184.png)

How do I set this to get rid of this distance？

**Comment by minikin** [comment]
@superxsx Thank you for your report. 
The recent maxWidth and maxHeight for popover are :
```dart
 maxHeight: Utils().screenHeight / 2,
 maxWidth: Utils().screenHeight / 2,
```

**Comment by minikin** [comment]
I'm not quite sure what is the exact issue you have. So I'm closing it. 
Feel free to fire a new issue with a more detailed description. Thank you!
