### ISSUE TITLE
Leave the button on top of the barrier

### ISSUE THREAD

**Issue by mlorthios** [minikin/popover#39]
Hi, 

Is it possible to add the possibility to leave the button on top of the barrier?

Thanks

<img width="324" alt="Screenshot at Jun 19 13-20-02" src="https://user-images.githubusercontent.com/31793724/122640674-1e646300-d101-11eb-8f1a-8f2bb5fc6680.png">

**Comment by minikin** [comment]
@mlorthios Thank you for your request! 
I'm not quite sure what exact behavior do you want to achieve. Could you explain it in a bit more detail, please?

**Comment by mlorthios** [comment]
Currently the button that performs the action goes below the background carrier, only I would like to have the possibility to make the button go above so that it keeps its initial color. 

Example: 
![Screenshot from 2021-06-21 11-55-11](https://user-images.githubusercontent.com/31793724/122743798-a1afc100-d287-11eb-9ac7-2b41a04c1a82.png)

**Comment by minikin** [comment]
@mlorthios You can set `barrierColor : Colors.transparent`. It should keep the original color of a button.

**Comment by mlorthios** [comment]
Right, only as on the web version I have several buttons that propose a popover, the buttons where the popover are not active, them, remains under the popover, it is only the button said active which passes above, I do not know if it is feasible enough

**Comment by minikin** [comment]
@mlorthios Do you want to make it possible to tap on other buttons when one popover is open, right? 🤔

**Comment by mlorthios** [comment]
No, sorry for my English lol, the button that opens the popover is the only one to stay above the barrier color, the rest of the application remains below, on the screen above that I sent from my website, the barrier is light blue and the button remains in its normal state without the barrier going above

**Comment by minikin** [comment]
@mlorthios I got you. It doesn't sound to me like a popover issue. What you probably can do that try to change a color of a button when a popover is shown. I believe it should be possible to find a color for a button which in combination with barrierColor would produce the desired color.

**Comment by minikin** [comment]
@mlorthios I'm closing the issue for now.
