### ISSUE TITLE
type 'RenderSliverList' is not a subtype of type 'RenderBox' in type cast

### ISSUE THREAD

**Issue by yys730** [minikin/popover#42]
When the exception was thrown, this was the stack: 
#0      _PopoverItemState._configure (package:popover/src/popover_item.dart:86:51)
#1      _PopoverItemState.build.<anonymous closure> (package:popover/src/popover_item.dart:55:9)
#2      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:121:31)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
#4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)

I called it on e button in a list item like:
IconButton(
                      splashRadius: 24,
                      icon: Image.asset(
                        'assets/images/icon_more.png',
                        width: 20,
                      ),
                      onPressed: () {
                        showPopover(
                          context: context,
                          transitionDuration: const Duration(milliseconds: 150),
                          bodyBuilder: (context) => const ListItems(),
                          onPop: () => print('Popover was popped!'),
                          direction: PopoverDirection.top,
                          width: 200,
                          height: 400,
                          arrowHeight: 15,
                          arrowWidth: 30,
                        );
                      },
                    ),

**Comment by minikin** [comment]
@yys730 thanks for the report. Unfortunately, the provided information is not enough to fully understand the issue.
Would you be willing to showcase your problem [here](https://github.com/minikin/popover_playground), pls ?

**Comment by minikin** [comment]
@yys730 Closing it for now. Feel free to reopen it if this issue is still important.
