### ISSUE TITLE
Add fade animation as an alternative to default scale one

### ISSUE THREAD

**Issue by prateekmedia** [minikin/popover#48]
**Is your feature request related to a problem? Please describe.**
Popover used in gtk apps has a fade transition to open instead of scale one, So this package doesn't match consisitency.

**Describe the solution you'd like**
Add a way for users to specify there own transitions or add default transitions enum which contains Scale and Fade as a value and user can choose that when calling showPopover.

**Describe alternatives you've considered**
...

**Additional context**
Libadwaita library uses fade animation for the popover so we need it.

**Comment by minikin** [comment]
@prateekmedia That sounds like a good idea. One thing which I'd like to propose is to make it possible to pass any type of animation and keep scaling as the default one. Would you like to create a pr?

**Comment by prateekmedia** [comment]
@minikin That will be good but I dont know how this would work or where to start. 

I have created a fork to do so where I have replaced scale with fade but that is currently a Hack and not a good implementation.

**Comment by prateekmedia** [comment]
@minikin Can you point me where to get started to add this feature.
