### ISSUE TITLE
Error when parent is removed even with isParentAlive: () => mounted

### ISSUE THREAD

**Issue by JFtechOfficial** [minikin/popover#53]
**Describe the bug**
the "red screen of death" appears when parent widget is removed and popover is shown.

**To Reproduce**
1. a ListView.builder generates a variable number of stateful widgets based on a list (provided by a BlocBuilder). Each of these widgets contains an InkWell with showPopover associated to the onTap parameter. in the body of the popover a BlocListener is present to ensure that, if the list changes and the parent widget is removed, the popover uses navigator.pop to pop itself immediately;
2. the user taps on one of the InkWell and the popover appears;
3. the list updates, the parent widget should be removed;
4. ListView.builder rebuilds, removing the appropriate element;
5. popover throws the following error just before popping itself, even if isParentAlive is set to () => mounted. The same error happens when, without using navigator.pop inside the BlocListener, is the user that taps outside the popover area after parent is removed;

`======== Exception caught by widgets library =======================================================
The following assertion was thrown building LayoutBuilder:
Cannot get renderObject of inactive element.

In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
Instead, this element is in the _ElementLifecycle.inactive state.
If you called this method from a State object, consider guarding it with State.mounted.
The findRenderObject() method was called for the following element: PlayerStory
  dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#e783b]]
  state: _PlayerStoryState#a1542
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/gianlucagalli/AndroidStudioProjects/hero_realms_life_counter/lib/main.dart:104:18
When the exception was thrown, this was the stack: 
#0      Element.findRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:4039:9)
#1      Element.findRenderObject (package:flutter/src/widgets/framework.dart:4052:6)
#2      _PopoverItemState._configure (package:popover/src/popover_item.dart:100:32)
#3      _PopoverItemState.build.<anonymous closure> (package:popover/src/popover_item.dart:57:9)
#4      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:119:77)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#6      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
#7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2025:59)
#8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2025:14)
#10     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:227:7)
#11     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316:5)
#12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#23     _invoke (dart:ui/hooks.dart:151:10)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#25     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================`
**Expected behavior**
popover not throwing exceptions

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 10

**Additional context**
here is the code:
```dart
//...
ListView.builder(
                physics: const BouncingScrollPhysics(),
                scrollDirection: Axis.horizontal,
                //shrinkWrap: true,
                controller: _scrollController,
                itemCount: playersList.length,
                itemBuilder: (BuildContext context, int index) {
                  return PlayerStory(user: playersList[index].user);
                },
              ),
//...
```

```dart
class PlayerStory extends StatefulWidget {
  const PlayerStory({
    super.key,
    required this.user,
  });

  final User user;

  @override
  State<PlayerStory> createState() => _PlayerStoryState();
}

class _PlayerStoryState extends State<PlayerStory> {
  @override
  Widget build(BuildContext context) {
    double avancedAvatarSize = 17.w;
    double dyOffset = -10.0;
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: InkWell(
        onTap: () {
          showPopover(
            context: context,
            transitionDuration: const Duration(milliseconds: 150),
            backgroundColor: Theme.of(context).primaryColor,
            bodyBuilder: (ctx) {
              return MultiBlocProvider(
                providers: [
                  BlocProvider.value(
                    value: BlocProvider.of<HealthCalculationCubit>(context),
                  ),
                  BlocProvider.value(
                    value: BlocProvider.of<UserBloc>(context),
                  ),
                  BlocProvider.value(
                    value: BlocProvider.of<PlayersBloc>(context),
                  ),
                  BlocProvider.value(
                    value: BlocProvider.of<GameBloc>(context),
                  ),
                ],
                child: Padding(
                  padding: const EdgeInsets.all(30.0),
                  child: BlocListener<PlayersBloc, PlayersState>(
                    listener: (ctx, state) {
                      if (state.players!.every(
                          (player) => player!.user!.id != widget.user.id)) {
                        Navigator.pop(ctx);
                      }
                    },
                    child: Container(//...
                    ),
                  ),
                ),
              );
            },
            onPop: () => print('Popover was popped!'),
            isParentAlive: () => mounted,
            direction: PopoverDirection.bottom,
            radius: 5.w,
            width: 90.w,
            arrowDyOffset: dyOffset,
            contentDyOffset: dyOffset,
          );
        },
        child: AnimatedContainer(//...
        ),
      ),
    );
  }
}
```

**Comment by Pierre2tm** [comment]
same problem

**Comment by minikin** [comment]
@JFtechOfficial @Pierre2tm 
Thank you for the report. Feel free to fix the issue and make a PR.

**Comment by ajaxspace** [comment]
@JFtechOfficial  @Pierre2tm 
Please try with this.

mixin PopoverParentState<T extends StatefulWidget> on State<T> {
  bool get isParentAlive => _isActive && mounted;

  bool _isActive = false;

  @override
  void initState() {
    super.initState();

    _isActive = true;
  }

  @override
  void activate() {
    super.activate();

    _isActive = true;
  }

  @override
  void deactivate() {
    _isActive = false;

    super.deactivate();
  }

  @override
  void dispose() {
    _isActive = false;

    super.dispose();
  }
}


 isParentAlive: () => isParentAlive,

**Comment by southxzx** [comment]
Im facing the same issue!

**Comment by minikin** [comment]
@southxzx Feel free to create a PR with the fix.
