### ISSUE TITLE
not showing any popover

### ISSUE THREAD

**Issue by jayu1023** [minikin/popover#54]
when i try to show by calling showPopOver()
i got just effect like alert dialog box not and popover 
so pls solve this issue i searched lots of but i can not find solution out there.

**Comment by minikin** [comment]
@jayu1023 Thank you for the report. Please, provide a more detailed issue description.


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by rajdeveloper92** [comment]
Hey @minikin  I also had the same issue let me share you details regarding the issue.

Desktop (please complete the following information):

OS: MacOs  13.0.1 (22A400) 
Browser : Chrome

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0.1 22A400 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (2 available)
    ! Error: Kishan’s iPhone is busy: Waiting to connect and unlock the device. Xcode will continue when Kishan’s iPhone is finished. (code -10)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by dylanalizon** [comment]
Same problem on iPad, i just followed the example in the README.md. The overlay was showing but the menu stay invisible ...

**Comment by benedict1986** [comment]
Hi everyone, I recently faced the same problem in Android and realised that I need to extract the popover to a widget. Here is what I did and hope it makes sense.

Before extracting, I have

```
return Scaffold(
      appBar: AppBar(title: GetBuilder<SettingsPageController>(
        builder: (SettingsPageController ctrl) {
          return ElevatedButton(
            child: Text('hello'),
            onPressed: () async {
              final double popupWidth = MediaQuery.of(context).size.width;

              await showPopover(
                backgroundColor: Colors.white,
                context: context,
                constraints: const BoxConstraints(maxHeight: 445),
                transitionDuration: const Duration(milliseconds: 150),
                width: 200,
                direction: PopoverDirection.bottom,
                bodyBuilder: (_) => Padding(
                    padding: EdgeInsets.symmetric(horizontal: 20),
                    child: ColoredBox(color: Colors.white, child: Text('hello'))),
              );
            },
          );
        },
      )),
      backgroundColor: const Color.fromARGB(255, 200, 200, 200),
      body: Text('hello'),
    );
```
Before clicking the button
![image](https://user-images.githubusercontent.com/7417859/207498908-4df9e762-83e3-4483-87e5-852aea20c20a.png)

After clicking the button
![image](https://user-images.githubusercontent.com/7417859/207498985-a0713720-5588-4ce2-89eb-1aa3b4aa3cb1.png)


Then I got exactly what @rajdeveloper92 shown in the video. I got a dark overlay and no popup.

After that, I extracted the button into a separate widget and then use the widget in the page. It started working

```
import 'package:flutter/material.dart';
import 'package:popover/popover.dart';

class PopoverWidget extends StatelessWidget {
  const PopoverWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: Text('hello'),
      onPressed: () async {
        final double popupWidth = MediaQuery.of(context).size.width;

        await showPopover(
          backgroundColor: Colors.white,
          context: context,
          constraints: const BoxConstraints(maxHeight: 445),
          transitionDuration: const Duration(milliseconds: 150),
          width: 200,
          direction: PopoverDirection.bottom,
          bodyBuilder: (_) => Padding(
              padding: EdgeInsets.symmetric(horizontal: 20),
              child: ColoredBox(color: Colors.white, child: Text('helo'))),
        );
      },
    );
  }
}
```

Then I applied the widget in my page
```
return Scaffold(
      appBar: AppBar(title: GetBuilder<SettingsPageController>(
        builder: (SettingsPageController ctrl) {
          return PopoverWidget();
        },
      )),
      backgroundColor: const Color.fromARGB(255, 200, 200, 200),
      body: Text('hello'),
    );
```

Then I can see the popover
![image](https://user-images.githubusercontent.com/7417859/207499261-ae83ebd3-abe7-4147-b5fa-965aee1610a0.png)

**Comment by daga-hiwot** [comment]
I faced the same problem on android and @benedict1986 solution works for me.

**Comment by alierdogan7** [comment]
@minikin  Hello Oleksandr, could you add this workaround information to the project's readme file? This issue also caused me time loss until I found this page. 

Thanks for this great package. It's very useful! 👍️
