### ISSUE TITLE
popover ^0.2.8 which doesn't match any versions

### ISSUE THREAD

**Issue by pkvv** [minikin/popover#58]
I tried to install popover of version 0.2.8 
But showing error as "example depends on popover ^0.2.8 which doesn't match any versions, version solving failed.
popover: ^0.2.8)" on  after flutter pub get

is this version not available?

**Comment by minikin** [comment]
It's not published yet. My suggestion is to use the latest version on [pub.dev](https://pub.dev/packages/popover/changelog) or add the package as a git dependency.
