### ISSUE TITLE
backgrounColor only effects arrow

### ISSUE THREAD

**Issue by hellohejinyu** [minikin/popover#59]
**Describe the bug**
Set the background color, only the arrow part takes effect.

**To Reproduce**
1. download example;
2. set backgroundColor to Colors.red;
3. run example;

**Expected behavior**
the popover is red

**Screenshots**
<img src="https://user-images.githubusercontent.com/8766034/212468722-399b8172-420d-46b7-8dfe-74b3d67514a6.png" width="300" />

```dart
showPopover(
  context: context,
  /// change here
  bodyBuilder: (context) => const SizedBox(
    width: 200,
    height: 400,
  ),
  onPop: () => print('Popover was popped!'),
  direction: PopoverDirection.bottom,
  /// change here
  backgroundColor: Colors.red,
  width: 200,
  height: 400,
  arrowHeight: 15,
  arrowWidth: 30,
);
```

**Comment by hellohejinyu** [comment]
https://github.com/minikin/popover/blob/de6471089227c57569f05466965f66757653c592/lib/src/popover_item.dart#L75

I remove the `Material`, then it works fine.

**Comment by minikin** [comment]
@hellohejinyu Thank you for your report.
I'm sure that the Material widget is required in PopoverItem. Otherwise, we will have an exception.
Feel free to create a PR with the appropriate fix.

**Comment by socramm9** [comment]
I diden't have any issue removing the Material widget. But if it hast to stay you could use this:

```
child: Material(
    color: widget.backgroundColor,
    child: widget.child,
),
```

**Comment by minikin** [comment]
The bug was fixed in the [latest version](https://github.com/minikin/popover/releases/tag/v0.2.8%2B1). Thank you!
