### ISSUE TITLE
How to manually turn it off

### ISSUE THREAD

**Issue by wangjunjx8868** [minikin/popover#70]
**Is your feature request related to a problem? Please describe.**
How to manually turn it off
**Describe the solution you'd like**
click a button hide popover .

**Comment by minikin** [comment]
Please, read documentation https://pub.dev/documentation/popover/latest/popover/showPopover.html

**Comment by theashishsuthar** [comment]
Could you please describe more? i didn't find any way to close the pop over progrmaticallty

**Comment by justincbeck** [comment]
Sounds good. How can I tell if the popover is visible or not? I can't just blindly call `Navigator.of(context.pop();`.

**Comment by LouisHaftmann** [comment]
You would typically call `Navigator.of(context).pop()` from within the popover.

**Comment by miaotaoii** [comment]
> The popover behaves just like a Flutter `Dialog`. So you can use `Navigator.of(context).pop();` to close it:
> 
> showPopover(
>   context: context,
>   bodyBuilder: (context) {
>     return ElevatedButton(
>       onPressed: () {
>         Navigator.of(context).pop();
>       },
>       child: Text('Close'),
>     );
>   },
> );
> just in case someone still needs this :)

how to pop it outside the widget
