### ISSUE TITLE
Odd/broken box shadow

### ISSUE THREAD

**Issue by maxim-saplin** [minikin/popover#77]
There're gaps in the shadow:

`shadow: [const BoxShadow(blurRadius: 40)],`
<img width="374" alt="image" src="https://github.com/minikin/popover/assets/7947027/717278c1-d921-4693-b6de-9415c8c0ae84">

and to make it more pronounced:
```
  shadow: [
    const BoxShadow(
        offset: Offset(30, 30), blurRadius: 0)
  ],
```

<img width="373" alt="image" src="https://github.com/minikin/popover/assets/7947027/b9e3bcfd-88d7-4ad8-a62c-cca05887dc94">

**Comment by minikin** [comment]
@maxim-saplin Is anything holding you back from implementing it and submitting a pull request?

**Comment by maxim-saplin** [comment]
I was passing by, no palns to invest time into this package :(

One more piece of feedback, there're no docs to APIs, figuring out what params mean by their name might be a challenge
