### ISSUE TITLE
[Bug]: half of the widget is not shown

### ISSUE THREAD

**Issue by AlaaSafory** [minikin/popover#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The popover widget doesn't abide by the constraints of the screen, half of it is not shown when the button is at the edge of the screen..
![1101bf63-0a8d-4899-8acb-bac0902bcecc](https://github.com/minikin/popover/assets/118113948/c33faf40-86b8-4fb3-b7de-caf3e427ad9b)

### Expected Behavior

This only happened when I updated to the latest flutter version and updated the package to the lastest version, it used to work correctly before now I'm experiencing this issue even when used the code shown in the example of the package..

### What operating system are you seeing the problem on?

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fleeser** [comment]
Same here!

**Comment by manudicri** [comment]
Same here!

**Comment by minikin** [comment]
Thank you for the report. Feel free to create a PR that addresses this issue.

**Comment by Ehrax** [comment]
Same here! Any updates here? 🤔

**Comment by minikin** [comment]
@Ehrax, is there anything that is stopping you from fixing the issue? 
I'm happy to review a PR. However, I don't have time to work on the fix.

**Comment by Ehrax** [comment]
@minikin I could try, but I am not 100% what is causing this or where too look into, did not had proper time to investigate it yet. Is it for you maybe possible to forward me in the right direction? ✌️

**Comment by minikin** [comment]
@Ehrax you probably need to play with [popover_render_shifted_box](https://github.com/minikin/popover/blob/main/lib/src/popover_render_shifted_box.dart) and [popover_position_render_object](https://github.com/minikin/popover/blob/main/lib/src/popover_position_render_object.dart). Something has changed in this project or in of the latest Flutter versions.

**Comment by minikin** [comment]
fixed by #84
