### ISSUE TITLE
[Bug]: popover can not be showing

### ISSUE THREAD

**Issue by lucasjinreal** [minikin/popover#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

just balck scrrens

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```sh
bhvoiu
```

### Anything else?

jjlojhpuoui

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucasjinreal** [comment]
@minikin Any suggestions?

**Comment by Hamid313-coder** [comment]
For me it fixed when I created a seprated widget for the button to be shown.

I copied the same code from example but with no seprated button widget and it wasn't showing the dialog but when I made the button part another widget it appeared on the screen.
I think it's something related to the widget tree
